server:
  port: 8080 # 스프링 서버 포트 번호

cors:
  allowed-origins: ${FRONTEND_URL:http://localhost:5173}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: cherryFallDetectionSystemSecretKeyForJwtAuthentication
  expiration-time: 3600000