server:
  port: 8080 # 스프링 서버 포트 번호

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cherry_db
    username: root # 보통 로컬은 root 입니다.
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update # 엔티티(Entity) 클래스를 보고 자동으로 DB에 테이블을 만들어줌!
    show-sql: true # JPA가 내부적으로 실행하는 SQL 쿼리문을 콘솔창에 보여줌
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 줄바꿈해서 출력해줌

jwt:
  secret: cherryFallDetectionSystemSecretKeyForJwtAuthentication
  expiration-time: 3600000